### ISSUE TITLE
Setting up resources needs to be simplified.

### ISSUE THREAD

**Issue by kherge** [kherge-php/sleep-bundle#2]
## Problem

When a new resource is created, there are many new classes that need to be registered as a service and possibly tagged. In an application where dozens of resources may be necessary, the process of creating and registering these services can be tedious and repetitive.

## Resolution

The dependency container extension for the bundle should provide the ability to specify resources and their respective classes for registration processing by the extension. This will, at the very least, reduce the process to modifying a single configuration file.

## Stretch Goal

The Doctrine bundle is capable of automatically registering entities and making them available to the application. If this bundle could implement something similar for resources, it could completely eliminate the need for any developer involvement. This would probably require a predefined directory structure for it to work.

**Comment by kherge** [comment]
Dependent on:
- FriendsOfSymfony/FOSRestBundle#1695
- FriendsOfSymfony/FOSRestBundle#1696

**Comment by kherge** [comment]
I am maintaining a fork with my pull request in the mean time. At some point I will want to evaluate how I can change route name generation by creating a class, or set of classes, that will plug right in to FOSRestBundle through the service container.

**Comment by kherge** [comment]
To help me understand what it is I need to reduce in order to simplify the setup process, I am documenting the process of creating a resource and then making it available.

## Example Directory Structure

This structure is just to help illustrate the steps used during the creation process.

```
/path/to/webapp/src/My/Bundle/ExampleBundle/
    Form/
        Type/
            ExampleType.php
    Repository/
        ExampleRepository.php
    Resource/
        Example.php
```

## Steps

These are the steps I took. It may be possible to alter or remove the steps listed and maintain their effects. In fact, removing steps is the goal for the discovery process.

1. Create a new resource class by implementing `ResourceInterface`.
2. Create a new repository for the resource by implementing `ResourceRepositoryInterface`.
3. Register the repository as a service.
    ```yaml
    my_example.resource.example_repository:
        class: My\Bundle\ExampleBundle\Repository\ExampleRepository
    ```
4. Create a new form type for the resource as appropriate.
5. Register a new transformer for the resource.
    ```yaml
    my_example.resource.example_transformer:
        class: KHerGe\Bundle\SleepBundle\Resource\ResourceTransformer
        arguments:
            - '@property_accessor'
            - My\Bundle\ExampleBundle\Resource\Example
    ```
6. Register a new form factory for the resource.
    ```yaml
    my_example.resource.example_form_factory:
        class: KHerGe\Bundle\SleepBundle\Resource\ResourceFormFactory
        arguments:
            - '@form.factory'
            - My\Bundle\ExampleBundle\Form\Type\ExampleType
            - '@my_example.resource.example_transformer'
    ```
7. Register a new controller for the resource.
    ```yaml
    my_example.resource.example_controller:
        parent: kherge.sleep.resource_controller
        calls:
            - ['setResourceClass', ['My\Bundle\ExampleBundle\Resource\Example']]
            - ['setResourceFormFactory', ['@my_example.resource.example_form_factory']]
            - ['setResourceRepository', ['@my_example.resource.example_repository']]
            - ['setResourceTransformer', ['@my_example.resource.example_transformer']]
    ```

**Comment by kherge** [comment]
The following bundle configuration can be used for each resource:

```yaml
kherge_sleep:
    resources:

        # Repeat configuration pattern for each resource.
        My\Bundle\ExampleBundle\Resource\Example:
            form: My\Bundle\ExampleBundle\Form\Type\ExampleType
            repository: My\Bundle\ExampleBundle\Repository\ExampleRepository

            # The following is automatically set but can be overridden if needed.
            # controller: KHerGe\Bundle\SleepBundle\Controller\ResourceController
            # transformer: KHerGe\Bundle\SleepBundle\Resource\ResourceTransformer
```

The `KHerGeSleepExtension` bundle extension can use the settings to automatically create new services during container compilation. Using the above example, the service identifiers will be automatically generated. If custom identifiers are required, the following example could be used.

```yaml
kherge_sleep:
    resources:

    My\Bundle\ExampleBundle\Resource\Example:
        form:
            name: my_example.resource.example_form_factory
            class: My\Bundle\ExampleBundle\Form\Type\ExampleType
        repository:
            name: my_example.resource.example_repository
            class: My\Bundle\ExampleBundle\Repository\ExampleRepository

        # controller:
        #     name: my_example.resource.example_controller
        #     class: KHerGe\Bundle\SleepBundle\Controller\ResourceController
        # transformer:
        #     name: my_example.resource.example_transformer
        #     class: KHerGe\Bundle\SleepBundle\Resource\ResourceTransformer
```
