### ISSUE TITLE
Reconsider defined roles for resources.

### ISSUE THREAD

**Issue by kherge** [kherge-php/sleep-bundle#6]
## Problem

The resource voter uses the following role name templates for resources:

    ROLE_%s_ADMIN
    ROLE_%s_DELETE
    ROLE_%s_READ
    ROLE_%s_WRITE

The naming convention may not be adequate and since they are dynamically generated, may conflict with other roles of a similar name.

## Resolution

Make the role name templates configurable through a bundle configuration setting.

```yaml
kherge_sleep:
    roles:
        admin: 'ROLE_%s_ADMIN'

        delete: 'ROLE_%s_DELETE'
        list: 'ROLE_%s_READ'
        read: 'ROLE_%s_READ'
        write: 'ROLE_%s_WRITE'
```

It should also be possible to set the `admin` role to `null` so that no admin role for the resource is defined. This will allow the application developer to define their own role hierarchy. As implemented right now, there is no flexibility.

```yaml
security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_EXAMPLE_DELETE
            - ROLE_EXAMPLE_READ
            - ROLE_EXAMPLE_WRITE
```

### Defaults

The default bundle settings for this feature should be:

```yaml
kherge_sleep:
    roles:
        admin: 'ROLE_RESOURCE_%s_ADMIN'
        list: 'ROLE_RESOURCE_%s_LIST'
        read: 'ROLE_RESOURCE_%s_READ'
        write: 'ROLE_RESOURCE_%s_WRITE'
```

## References

- [The security resource voter.](https://github.com/kherge-php/sleep-bundle/blob/f6eabe4691586885f8fd0662dcbf6aee36c0ae2b/Security/Authorization/Voter/ResourceVoter.php#L181-L247)

**Comment by kherge** [comment]
Because the `read` role can be used to circumvent the lack of `list` role privileges, there will be no separate `list` role.

**Comment by kherge** [comment]
Opting to use roles named after CRUD operations:

```yaml
kherge_sleep:
    roles:
        admin: 'ROLE_RESOURCE_%s_ADMIN'

        create: 'ROLE_RESOURCE_%s_CREATE'
        read: 'ROLE_RESOURCE_%s_READ'
        update: 'ROLE_RESOURCE_%s_UPDATE'
        delete: 'ROLE_RESOURCE_%s_DELETE'
```

This will require that the resource controller understand the difference between creating a new resource and updating an existing one.

- [patchAction()](https://github.com/kherge-php/sleep-bundle/blob/master/Controller/ResourceController.php#L136)
- [putAction()](https://github.com/kherge-php/sleep-bundle/blob/master/Controller/ResourceController.php#L204)
